version: '3.8'

services:
  web:
    container_name: "mr_web"
    build: ./
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./:/usr/src/app/
      - /usr/src/app/node_modules
    ports:
      - 8000:8000
    env_file:
      - ./.env
    depends_on:
      # - db
      - cache
    links:
      # - db
      - cache
  # db:
  #   container_name: "mr_db"
  #   image: postgres
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data/
  #   env_file:
  #     - ./.env
  cache:
    container_name: "mr_cache"
    image: redis:7.2-alpine
    ports:
      - 6379:6379
    command: redis-server --save 20 1 --loglevel warning
    volumes: 
      - cache:/data

volumes:
  cache:
    driver: local
  postgres_data:
