# Generated by Django 4.2.1 on 2023-05-25 19:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_limit', models.PositiveSmallIntegerField()),
                ('category_limit', models.PositiveSmallIntegerField()),
                ('shuffle_cards', models.BooleanField()),
                ('guess_mode', models.BooleanField()),
                ('host', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('points', models.PositiveSmallIntegerField()),
                ('cookie', models.CharField(max_length=200)),
                ('game_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basicgame.game')),
            ],
        ),
    ]
