# Generated by Django 4.2.1 on 2023-05-30 12:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basicgame', '0003_alter_game_name_alter_player_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='card_limit',
            new_name='round_length',
        ),
        migrations.RenameField(
            model_name='game',
            old_name='guess_mode',
            new_name='boring',
        ),
        migrations.RemoveField(
            model_name='game',
            name='category_limit',
        ),
        migrations.RemoveField(
            model_name='game',
            name='shuffle_cards',
        ),
        migrations.AlterField(
            model_name='game',
            name='name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='player',
            name='name',
            field=models.CharField(max_length=100, unique=True, validators=[django.core.validators.RegexValidator('^[A-Za-z0-9_-]+$', "Letters, numbers, '_' and '-' only please")]),
        ),
    ]
