# Generated by Django 4.2.1 on 2023-05-30 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basicgame', '0004_rename_card_limit_game_round_length_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='game_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='basicgame.game'),
        ),
    ]
