# Generated by Django 4.2.1 on 2023-06-01 08:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basicgame', '0005_alter_player_game_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='progress',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='game',
            name='name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='player',
            name='game_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='basicgame.game'),
        ),
    ]
