# Generated by Django 4.2.1 on 2023-06-06 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basicgame', '0008_alter_player_submission'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='cookie',
        ),
    ]
