# Generated by Django 4.2.1 on 2023-06-09 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basicgame', '0009_remove_player_cookie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='submission',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
