# Generated by Django 4.2.1 on 2023-06-15 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basicgame', '0010_alter_player_submission'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='votes',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='submission',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
