# Generated by Django 4.2.1 on 2023-06-20 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basicgame', '0011_player_votes_alter_player_submission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='progress',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
