# Generated by Django 4.2.1 on 2023-07-01 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basicgame', '0012_alter_game_progress'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='round_length',
            new_name='rounds',
        ),
    ]
