# Generated by Django 4.2.1 on 2023-08-25 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basicgame', '0013_rename_round_length_game_rounds'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='rounds',
            new_name='cycles',
        ),
        migrations.AlterField(
            model_name='game',
            name='progress',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
    ]
